const $ = (s)=>document.querySelector(s);
const app = $('#app');
const unitFilter = $('#unitFilter');
const dirFilter = $('#directionFilter');
const LS='chinese_exam_progress_v1';
let tab='cards', current=null, flipped=false, chosen=[];
let progress = JSON.parse(localStorage.getItem(LS)||'{}');

for(let i=1;i<=5;i++){ const o=document.createElement('option'); o.value=i; o.textContent='Einheit '+i; unitFilter.appendChild(o); }
function save(){localStorage.setItem(LS,JSON.stringify(progress)); renderStats();}
function key(item,type='v'){return type+':'+item.u+':'+item.h;}
function mark(item,ok,type='v'){const k=key(item,type); progress[k]=progress[k]||{ok:0,bad:0}; ok?progress[k].ok++:progress[k].bad++; save();}
function pool(arr){let u=unitFilter.value; return arr.filter(x=>u==='all'||String(x.u)===u);}
function pick(arr){arr=pool(arr); return arr[Math.floor(Math.random()*arr.length)];}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function norm(s){return (s||'').trim().toLowerCase().replace(/[，。！？?！.,;；:：\s]/g,'');}
function renderStats(){
 let vals=Object.values(progress), ok=vals.reduce((a,b)=>a+b.ok,0), bad=vals.reduce((a,b)=>a+b.bad,0);
 let mastered=Object.entries(progress).filter(([k,v])=>v.ok>=3 && v.ok>v.bad).length;
 $('#stats').innerHTML=`<div class="stat"><b>${VOCAB.length}</b><span>Vokabeln</span></div><div class="stat"><b>${SENTENCES.length}</b><span>Sätze</span></div><div class="stat"><b>${ok}/${bad}</b><span>richtig/falsch</span></div><div class="stat"><b>${mastered}</b><span>beherrscht</span></div>`;
}
function src(u){return `<div class="source">Quelle: Einheit ${u}</div>`}
function render(){
 if(tab==='cards') return renderCards(); if(tab==='write') return renderWrite(); if(tab==='order') return renderOrder(); if(tab==='cloze') return renderCloze(); if(tab==='dialogue') return renderDialogue(); if(tab==='exam') return renderExam(); if(tab==='list') return renderList();
}
function getCardPrompt(v){
 let mode=dirFilter.value; if(mode==='mixed') mode=['hanzi-de','de-hanzi','pinyin-hanzi'][Math.floor(Math.random()*3)];
 if(mode==='hanzi-de') return {q:v.h, sub:v.p, ans:v.d, type:'Bedeutung'};
 if(mode==='de-hanzi') return {q:v.d, sub:'Deutsch → Hanzi', ans:v.h+' · '+v.p, type:'Hanzi'};
 return {q:v.p, sub:'Pinyin → Hanzi', ans:v.h+' · '+v.d, type:'Hanzi'};
}
function renderCards(){ current=pick(VOCAB); flipped=false; drawCard(); }
function drawCard(){ let c=getCardPrompt(current); app.innerHTML=`<h2>Flashcards</h2><div class="card" id="flip"><div class="hanzi">${c.q}</div><div class="pinyin">${c.sub}</div>${flipped?`<div class="meaning">${c.ans}</div>`:''}</div>${src(current.u)}<div class="row"><button class="primary" id="show">${flipped?'Nächste Karte':'Antwort zeigen'}</button>${flipped?'<button id="ok">Gewusst</button><button id="bad">Nicht gewusst</button>':''}</div>`;
 $('#show').onclick=()=>{ if(flipped) renderCards(); else {flipped=true; drawCard();}}; $('#flip').onclick=()=>{$('#show').click()}; if(flipped){$('#ok').onclick=()=>{mark(current,true);renderCards()};$('#bad').onclick=()=>{mark(current,false);renderCards()};}
}
function renderWrite(){ current=pick(VOCAB); let c=getCardPrompt(current); app.innerHTML=`<h2>Schreibmodus</h2><div class="question">${c.q}</div><div class="small">Gesucht: ${c.type}</div><input id="answer" autocomplete="off" placeholder="Antwort eintippen"><div id="fb" class="feedback"></div>${src(current.u)}<div class="row"><button class="primary" id="check">Prüfen</button><button id="next">Weiter</button></div>`; $('#check').onclick=()=>{let val=$('#answer').value; let ans=c.ans; let ok=norm(ans).includes(norm(val))||norm(val).includes(norm(current.h))||norm(val).includes(norm(current.d)); $('#fb').innerHTML= ok?`<span class="ok">Richtig.</span> ${ans}`:`<span class="bad">Falsch.</span> Richtig: ${ans}`; mark(current,ok)}; $('#next').onclick=renderWrite; $('#answer').focus();}
function renderOrder(){ current=pick(SENTENCES); chosen=[]; drawOrder(); }
function drawOrder(){ let words=current.h.replace(/[。？！]/g,'').split(/(?=[\u4e00-\u9fff])/).filter(Boolean); if(words.length>12) words=current.h.replace(/[，。？！]/g,'').match(/.{1,2}/g)||words; let chips=shuffle(words); app.innerHTML=`<h2>Satzbau</h2><div class="small">Baue den Satz: ${current.d}</div><div class="target" id="target"></div><div class="chips">${chips.map(w=>`<button class="chip">${w}</button>`).join('')}</div><div id="fb" class="feedback"></div>${src(current.u)}<div class="row"><button class="primary" id="check">Prüfen</button><button id="clear">Zurücksetzen</button><button id="next">Weiter</button></div>`; document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{chosen.push(b.textContent); b.classList.add('used'); b.disabled=true; $('#target').innerHTML=chosen.map(x=>`<span class="chip">${x}</span>`).join('')}); $('#check').onclick=()=>{let ok=norm(chosen.join(''))===norm(current.h); $('#fb').innerHTML=ok?`<span class="ok">Richtig.</span>`:`<span class="bad">Falsch.</span> Richtig: ${current.h} (${current.p})`; mark(current,ok,'s')}; $('#clear').onclick=drawOrder; $('#next').onclick=renderOrder; }
function renderCloze(){ current=pick(SENTENCES); let chars=[...current.h].filter(ch=>/[\u4e00-\u9fff]/.test(ch)); let missing=chars[Math.floor(Math.random()*chars.length)]; let blank=current.h.replace(missing,'___'); app.innerHTML=`<h2>Lückentext</h2><div class="question hanzi">${blank}</div><div class="small">Bedeutung: ${current.d}</div><input id="answer" placeholder="fehlendes Hanzi"><div id="fb" class="feedback"></div>${src(current.u)}<div class="row"><button class="primary" id="check">Prüfen</button><button id="next">Weiter</button></div>`; $('#check').onclick=()=>{let ok=norm($('#answer').value)===norm(missing); $('#fb').innerHTML=ok?`<span class="ok">Richtig.</span>`:`<span class="bad">Falsch.</span> Richtig: ${missing} → ${current.h}`; mark(current,ok,'c')}; $('#next').onclick=renderCloze; $('#answer').focus();}
function renderDialogue(){ current=pick(DIALOGUE_Q); app.innerHTML=`<h2>Dialogfragen</h2><div class="question">${current.q}</div><input id="answer" placeholder="Antwort auf Chinesisch"><div id="fb" class="feedback"></div>${src(current.u)}<div class="row"><button class="primary" id="check">Prüfen</button><button id="next">Weiter</button></div>`; $('#check').onclick=()=>{let ok=norm($('#answer').value)===norm(current.a); $('#fb').innerHTML=ok?`<span class="ok">Richtig.</span>`:`<span class="bad">Falsch.</span> Richtig: ${current.a}`; mark({u:current.u,h:current.q},ok,'d')}; $('#next').onclick=renderDialogue; $('#answer').focus();}
let exam={qs:[],i:0,ok:0,bad:0,wrong:[]};
function makeExamQ(){let type=['v','s','c','d'][Math.floor(Math.random()*4)]; if(type==='v'){let v=pick(VOCAB); let right=v.d; let opts=shuffle([right,...shuffle(VOCAB.filter(x=>x!==v)).slice(0,3).map(x=>x.d)]); return {type,q:v.h+' · '+v.p, opts, ans:right, u:v.u};} if(type==='s'){let s=pick(SENTENCES); return {type,q:'Übersetze: '+s.d, ans:s.h, u:s.u, input:true};} if(type==='c'){let s=pick(SENTENCES); let chars=[...s.h].filter(ch=>/[\u4e00-\u9fff]/.test(ch)); let m=chars[Math.floor(Math.random()*chars.length)]; return {type,q:s.h.replace(m,'___')+' · '+s.d, ans:m, u:s.u, input:true};} let d=pick(DIALOGUE_Q); return {type,q:d.q, ans:d.a, u:d.u, input:true};}
function renderExam(start=false){ if(start){exam={qs:Array.from({length:25},makeExamQ),i:0,ok:0,bad:0,wrong:[]};} if(!exam.qs.length){app.innerHTML=`<h2>Klausurmodus</h2><p>25 gemischte Aufgaben aus allen Einheiten.</p><button class="primary" id="start">Starten</button>`; $('#start').onclick=()=>renderExam(true); return;} if(exam.i>=exam.qs.length){let pct=Math.round(exam.ok/exam.qs.length*100); app.innerHTML=`<h2>Ergebnis: ${pct}%</h2><p>Richtig: ${exam.ok} · Falsch: ${exam.bad}</p><div class="progressbar"><span style="width:${pct}%"></span></div><h3>Fehlerliste</h3>${exam.wrong.length?'<ul>'+exam.wrong.map(w=>`<li><b>${w.q}</b><br>Richtig: ${w.ans}</li>`).join('')+'</ul>':'<p>Keine Fehler.</p>'}<button class="primary" id="again">Neue Prüfung</button>`; $('#again').onclick=()=>renderExam(true); return;} let q=exam.qs[exam.i]; app.innerHTML=`<h2>Klausurmodus</h2><div class="small">Aufgabe ${exam.i+1}/${exam.qs.length} · Einheit ${q.u}</div><div class="question">${q.q}</div>${q.input?'<input id="answer" placeholder="Antwort"><div id="fb" class="feedback"></div><div class="row"><button class="primary" id="check">Prüfen</button></div>':`<div class="options">${q.opts.map(o=>`<button>${o}</button>`).join('')}</div><div id="fb" class="feedback"></div>`}`; function check(val){let ok=norm(val)===norm(q.ans); ok?exam.ok++:(exam.bad++,exam.wrong.push(q)); $('#fb').innerHTML=ok?'<span class="ok">Richtig.</span>':`<span class="bad">Falsch.</span> Richtig: ${q.ans}`; setTimeout(()=>{exam.i++; renderExam();},900)} if(q.input){$('#check').onclick=()=>check($('#answer').value); $('#answer').focus();} else document.querySelectorAll('.options button').forEach(b=>b.onclick=()=>check(b.textContent));}
function renderList(){ let rows=pool(VOCAB).map(v=>`<tr><td>${v.u}</td><td class="hanzi" style="font-size:24px">${v.h}</td><td>${v.p}</td><td>${v.d}</td></tr>`).join(''); app.innerHTML=`<h2>Vokabelliste</h2><table class="table"><thead><tr><th>Einheit</th><th>Hanzi</th><th>Pinyin</th><th>Deutsch</th></tr></thead><tbody>${rows}</tbody></table>`;}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active')); b.classList.add('active'); tab=b.dataset.tab; render();}); unitFilter.onchange=render; dirFilter.onchange=render; $('#resetBtn').onclick=()=>{if(confirm('Fortschritt wirklich löschen?')){progress={};save();render();}}; renderStats(); render();
