const VOCAB = [
// Unit 1
{u:1,h:'你好',p:'nǐ hǎo',d:'hello; hi'}, {u:1,h:'你',p:'nǐ',d:'you'}, {u:1,h:'好',p:'hǎo',d:'good; OK'},
{u:1,h:'请问',p:'qǐngwèn',d:'excuse me; may I ask?'}, {u:1,h:'请',p:'qǐng',d:'please; to invite'}, {u:1,h:'问',p:'wèn',d:'to ask'},
{u:1,h:'叫',p:'jiào',d:'to be called; to call'}, {u:1,h:'什么',p:'shénme',d:'what'}, {u:1,h:'名字',p:'míngzi',d:'name'},
{u:1,h:'我',p:'wǒ',d:'I; me'}, {u:1,h:'他',p:'tā',d:'he; him'}, {u:1,h:'她',p:'tā',d:'she; her'}, {u:1,h:'呢',p:'ne',d:'question particle; and you?'},
{u:1,h:'认识',p:'rènshi',d:'to know; to meet'}, {u:1,h:'很',p:'hěn',d:'very; quite'}, {u:1,h:'高兴',p:'gāoxìng',d:'happy; pleased'},
{u:1,h:'小姐',p:'xiǎojiě',d:'Miss; young lady'}, {u:1,h:'对不起',p:'duìbuqǐ',d:'sorry; excuse me'}, {u:1,h:'姓',p:'xìng',d:'surname; to be surnamed'},
{u:1,h:'中文',p:'Zhōngwén',d:'Chinese language'}, {u:1,h:'你们',p:'nǐmen',d:'you plural'}, {u:1,h:'是',p:'shì',d:'to be'}, {u:1,h:'大家',p:'dàjiā',d:'everyone'},
{u:1,h:'王',p:'Wáng',d:'Wang; a Chinese surname'}, {u:1,h:'玉',p:'Yù',d:'jade; Yu'}, {u:1,h:'马克',p:'Mǎkè',d:'Mark'},
// Unit 2
{u:2,h:'早上好',p:'zǎoshang hǎo',d:'good morning'}, {u:2,h:'日本',p:'Rìběn',d:'Japan'}, {u:2,h:'人',p:'rén',d:'person; people'},
{u:2,h:'日本人',p:'Rìběnrén',d:'Japanese person'}, {u:2,h:'吗',p:'ma',d:'yes-no question particle'}, {u:2,h:'不',p:'bù',d:'not; no'},
{u:2,h:'哪里',p:'nǎli',d:'where; from where'}, {u:2,h:'哪',p:'nǎ',d:'which'}, {u:2,h:'中国',p:'Zhōngguó',d:'China'}, {u:2,h:'中国人',p:'Zhōngguórén',d:'Chinese person'},
{u:2,h:'国',p:'guó',d:'country; nation'}, {u:2,h:'英国',p:'Yīngguó',d:'United Kingdom; Britain'}, {u:2,h:'英国人',p:'Yīngguórén',d:'British person'},
{u:2,h:'住',p:'zhù',d:'to live; to reside'}, {u:2,h:'在',p:'zài',d:'at; in; to be located'}, {u:2,h:'伦敦',p:'Lúndūn',d:'London'}, {u:2,h:'北京',p:'Běijīng',d:'Beijing'},
{u:2,h:'他们',p:'tāmen',d:'they; them'}, {u:2,h:'电影',p:'diànyǐng',d:'film; movie'}, {u:2,h:'明星',p:'míngxīng',d:'star; celebrity'},
{u:2,h:'电影明星',p:'diànyǐng míngxīng',d:'movie star'}, {u:2,h:'但是',p:'dànshì',d:'but'}, {u:2,h:'美国',p:'Měiguó',d:'United States; America'}, {u:2,h:'美国人',p:'Měiguórén',d:'American person'},
{u:2,h:'青岛',p:'Qīngdǎo',d:'Qingdao'}, {u:2,h:'香港',p:'Xiānggǎng',d:'Hong Kong'}, {u:2,h:'法国',p:'Fǎguó',d:'France'}, {u:2,h:'法国人',p:'Fǎguórén',d:'French person'},
{u:2,h:'德国',p:'Déguó',d:'Germany'}, {u:2,h:'德国人',p:'Déguórén',d:'German person'}, {u:2,h:'韩国',p:'Hánguó',d:'Korea'}, {u:2,h:'韩国人',p:'Hánguórén',d:'Korean person'},
{u:2,h:'澳大利亚',p:'Àodàlìyà',d:'Australia'}, {u:2,h:'加拿大',p:'Jiānádà',d:'Canada'}, {u:2,h:'瑞士',p:'Ruìshì',d:'Switzerland'},
// Unit 3
{u:3,h:'爸爸',p:'bàba',d:'dad; father'}, {u:3,h:'妈妈',p:'māma',d:'mom; mother'}, {u:3,h:'姐姐',p:'jiějie',d:'older sister'},
{u:3,h:'妹妹',p:'mèimei',d:'younger sister'}, {u:3,h:'哥哥',p:'gēge',d:'older brother'}, {u:3,h:'弟弟',p:'dìdi',d:'younger brother'},
{u:3,h:'这',p:'zhè',d:'this'}, {u:3,h:'和',p:'hé',d:'and; with'}, {u:3,h:'也',p:'yě',d:'also; too'}, {u:3,h:'学生',p:'xuésheng',d:'student; pupil'},
{u:3,h:'记者',p:'jìzhě',d:'journalist; reporter'}, {u:3,h:'做',p:'zuò',d:'to do; to make'}, {u:3,h:'工作',p:'gōngzuò',d:'work; job; to work'},
{u:3,h:'医生',p:'yīshēng',d:'doctor'}, {u:3,h:'医院',p:'yīyuàn',d:'hospital'}, {u:3,h:'都',p:'dōu',d:'all; both'},
{u:3,h:'家',p:'jiā',d:'family; home'}, {u:3,h:'的',p:'de',d:'possessive particle'}, {u:3,h:'照片',p:'zhàopiàn',d:'photo; photograph'},
{u:3,h:'学校',p:'xuéxiào',d:'school'}, {u:3,h:'老师',p:'lǎoshī',d:'teacher'}, {u:3,h:'什么工作',p:'shénme gōngzuò',d:'what job; what work'},
// Unit 4
{u:4,h:'谁',p:'shéi',d:'who; whom'}, {u:4,h:'上海',p:'Shànghǎi',d:'Shanghai'}, {u:4,h:'上海人',p:'Shànghǎirén',d:'person from Shanghai'}, {u:4,h:'现在',p:'xiànzài',d:'now'},
{u:4,h:'多大',p:'duō dà',d:'how old'}, {u:4,h:'岁',p:'suì',d:'years old'}, {u:4,h:'知道',p:'zhīdào',d:'to know'}, {u:4,h:'真',p:'zhēn',d:'really; truly'},
{u:4,h:'高',p:'gāo',d:'tall; high'}, {u:4,h:'帅',p:'shuài',d:'handsome'}, {u:4,h:'酷',p:'kù',d:'cool'}, {u:4,h:'最',p:'zuì',d:'most; -est'},
{u:4,h:'喜欢',p:'xǐhuan',d:'to like'}, {u:4,h:'篮球',p:'lánqiú',d:'basketball'}, {u:4,h:'运动员',p:'yùndòngyuán',d:'athlete; player'}, {u:4,h:'篮球运动员',p:'lánqiú yùndòngyuán',d:'basketball player'},
{u:4,h:'姓名',p:'xìngmíng',d:'full name'}, {u:4,h:'年龄',p:'niánlíng',d:'age'}, {u:4,h:'出生地',p:'chūshēngdì',d:'place of birth'},
{u:4,h:'国籍',p:'guójí',d:'nationality'}, {u:4,h:'电子邮箱',p:'diànzǐ yóuxiāng',d:'email address'}, {u:4,h:'动物',p:'dòngwù',d:'animal'},
{u:4,h:'熊猫',p:'xióngmāo',d:'panda'}, {u:4,h:'可爱',p:'kě’ài',d:'cute; lovely'}, {u:4,h:'演员',p:'yǎnyuán',d:'actor; actress'},
{u:4,h:'年轻',p:'niánqīng',d:'young'}, {u:4,h:'漂亮',p:'piàoliang',d:'pretty; beautiful'}, {u:4,h:'矮',p:'ǎi',d:'short; low'}, {u:4,h:'老',p:'lǎo',d:'old'},
{u:4,h:'姚明',p:'Yáo Míng',d:'Yao Ming'},
// Unit 5
{u:5,h:'电话',p:'diànhuà',d:'telephone; phone'}, {u:5,h:'电话号码',p:'diànhuà hàomǎ',d:'phone number'}, {u:5,h:'号码',p:'hàomǎ',d:'number; code'}, {u:5,h:'手机',p:'shǒujī',d:'mobile phone'},
{u:5,h:'手机号码',p:'shǒujī hàomǎ',d:'mobile phone number'}, {u:5,h:'多少',p:'duōshao',d:'how much; how many'}, {u:5,h:'公园',p:'gōngyuán',d:'park'}, {u:5,h:'路',p:'lù',d:'road; street; way'},
{u:5,h:'号',p:'hào',d:'number; date'}, {u:5,h:'新',p:'xīn',d:'new'}, {u:5,h:'地址',p:'dìzhǐ',d:'address'}, {u:5,h:'大学',p:'dàxué',d:'university'}, {u:5,h:'大学路',p:'Dàxué Lù',d:'University Road'},
{u:5,h:'公寓',p:'gōngyù',d:'apartment building'}, {u:5,h:'房间',p:'fángjiān',d:'room'}, {u:5,h:'可以',p:'kěyǐ',d:'can; may'}, {u:5,h:'给',p:'gěi',d:'to give; for; to'},
{u:5,h:'打电话',p:'dǎ diànhuà',d:'to make a phone call'}, {u:5,h:'发件人',p:'fājiànrén',d:'sender'}, {u:5,h:'收到',p:'shōudào',d:'to receive; received'},
{u:5,h:'谢谢',p:'xièxie',d:'thank you; thanks'}, {u:5,h:'收件箱',p:'shōujiànxiāng',d:'inbox'}, {u:5,h:'发送',p:'fāsòng',d:'to send'}, {u:5,h:'新短信',p:'xīn duǎnxìn',d:'new text message'}, {u:5,h:'退出',p:'tuìchū',d:'to exit; to log out'}
];

const SENTENCES = [
// Unit 1: greetings and names
{u:1,h:'你好！',p:'Nǐ hǎo!',d:'Hello!'}, {u:1,h:'大家好！',p:'Dàjiā hǎo!',d:'Hello everyone!'},
{u:1,h:'请问，你叫什么名字？',p:'Qǐngwèn, nǐ jiào shénme míngzi?',d:'Excuse me, what is your name?'},
{u:1,h:'你叫什么名字？',p:'Nǐ jiào shénme míngzi?',d:'What is your name?'}, {u:1,h:'我叫王玉。',p:'Wǒ jiào Wáng Yù.',d:'My name is Wang Yu.'},
{u:1,h:'我叫马克。',p:'Wǒ jiào Mǎkè.',d:'My name is Mark.'}, {u:1,h:'你呢？',p:'Nǐ ne?',d:'And you?'},
{u:1,h:'认识你很高兴。',p:'Rènshi nǐ hěn gāoxìng.',d:'Nice to meet you.'},
{u:1,h:'认识你们很高兴。',p:'Rènshi nǐmen hěn gāoxìng.',d:'Nice to meet you all.'},
{u:1,h:'对不起，我姓王。',p:'Duìbuqǐ, wǒ xìng Wáng.',d:'Sorry, my surname is Wang.'},
{u:1,h:'我姓王。',p:'Wǒ xìng Wáng.',d:'My surname is Wang.'}, {u:1,h:'我的中文名字是马克。',p:'Wǒ de Zhōngwén míngzi shì Mǎkè.',d:'My Chinese name is Mark.'},
{u:1,h:'中文名字是马克。',p:'Zhōngwén míngzi shì Mǎkè.',d:'The Chinese name is Mark.'},
// Unit 2: nationality and residence
{u:2,h:'早上好！',p:'Zǎoshang hǎo!',d:'Good morning!'}, {u:2,h:'你是日本人吗？',p:'Nǐ shì Rìběnrén ma?',d:'Are you Japanese?'},
{u:2,h:'不是，我不是日本人。',p:'Bú shì, wǒ bú shì Rìběnrén.',d:'No, I am not Japanese.'},
{u:2,h:'你是哪里人？',p:'Nǐ shì nǎli rén?',d:'Where are you from?'}, {u:2,h:'我是中国人。',p:'Wǒ shì Zhōngguórén.',d:'I am Chinese.'},
{u:2,h:'我是德国人。',p:'Wǒ shì Déguórén.',d:'I am German.'}, {u:2,h:'我是英国人。',p:'Wǒ shì Yīngguórén.',d:'I am British.'},
{u:2,h:'你是哪国人？',p:'Nǐ shì nǎ guó rén?',d:'What nationality are you?'},
{u:2,h:'你住在哪里？',p:'Nǐ zhù zài nǎli?',d:'Where do you live?'}, {u:2,h:'你住在伦敦吗？',p:'Nǐ zhù zài Lúndūn ma?',d:'Do you live in London?'},
{u:2,h:'不，我住在北京。',p:'Bù, wǒ zhù zài Běijīng.',d:'No, I live in Beijing.'}, {u:2,h:'我住在伦敦。',p:'Wǒ zhù zài Lúndūn.',d:'I live in London.'},
{u:2,h:'他们是电影明星。',p:'Tāmen shì diànyǐng míngxīng.',d:'They are movie stars.'}, {u:2,h:'但是他们不是美国人。',p:'Dànshì tāmen bú shì Měiguórén.',d:'But they are not American.'},
{u:2,h:'他是中国人，但是住在美国。',p:'Tā shì Zhōngguórén, dànshì zhù zài Měiguó.',d:'He is Chinese, but he lives in the United States.'},
// Unit 3: family and jobs
{u:3,h:'她是你妹妹吗？',p:'Tā shì nǐ mèimei ma?',d:'Is she your younger sister?'}, {u:3,h:'是，她是我妹妹。',p:'Shì, tā shì wǒ mèimei.',d:'Yes, she is my younger sister.'},
{u:3,h:'这是我弟弟。',p:'Zhè shì wǒ dìdi.',d:'This is my younger brother.'}, {u:3,h:'这是我家的照片。',p:'Zhè shì wǒ jiā de zhàopiàn.',d:'This is a photo of my family.'},
{u:3,h:'这是我爸爸和妈妈。',p:'Zhè shì wǒ bàba hé māma.',d:'These are my father and mother.'},
{u:3,h:'你妹妹和弟弟也是学生吗？',p:'Nǐ mèimei hé dìdi yě shì xuésheng ma?',d:'Are your younger sister and younger brother also students?'},
{u:3,h:'我弟弟是学生，但是我妹妹是记者。',p:'Wǒ dìdi shì xuésheng, dànshì wǒ mèimei shì jìzhě.',d:'My younger brother is a student, but my younger sister is a journalist.'},
{u:3,h:'你爸爸做什么工作？',p:'Nǐ bàba zuò shénme gōngzuò?',d:'What does your father do for work?'}, {u:3,h:'他是医生。',p:'Tā shì yīshēng.',d:'He is a doctor.'},
{u:3,h:'你妈妈在哪里工作？',p:'Nǐ māma zài nǎli gōngzuò?',d:'Where does your mother work?'}, {u:3,h:'她在医院工作。',p:'Tā zài yīyuàn gōngzuò.',d:'She works in a hospital.'},
{u:3,h:'爸爸妈妈都是医生。',p:'Bàba māma dōu shì yīshēng.',d:'Dad and mom are both doctors.'},
{u:3,h:'我爸爸是老师。',p:'Wǒ bàba shì lǎoshī.',d:'My father is a teacher.'}, {u:3,h:'我妈妈在学校工作。',p:'Wǒ māma zài xuéxiào gōngzuò.',d:'My mother works at a school.'},
// Unit 4: age, appearance, preferences
{u:4,h:'他是谁？',p:'Tā shì shéi?',d:'Who is he?'}, {u:4,h:'她是谁？',p:'Tā shì shéi?',d:'Who is she?'},
{u:4,h:'他是姚明，是吗？',p:'Tā shì Yáo Míng, shì ma?',d:'He is Yao Ming, right?'}, {u:4,h:'他是哪里人？',p:'Tā shì nǎli rén?',d:'Where is he from?'},
{u:4,h:'他是上海人。',p:'Tā shì Shànghǎirén.',d:'He is from Shanghai.'}, {u:4,h:'上海人，但是现在住在美国。',p:'Shànghǎirén, dànshì xiànzài zhù zài Měiguó.',d:'He is from Shanghai, but now he lives in the United States.'},
{u:4,h:'他多大？',p:'Tā duō dà?',d:'How old is he?'}, {u:4,h:'你多大？',p:'Nǐ duō dà?',d:'How old are you?'},
{u:4,h:'我不知道。',p:'Wǒ bù zhīdào.',d:'I do not know.'}, {u:4,h:'他真高！',p:'Tā zhēn gāo!',d:'He is really tall!'},
{u:4,h:'也很帅，很酷！',p:'Yě hěn shuài, hěn kù!',d:'Also very handsome and very cool!'}, {u:4,h:'她很漂亮。',p:'Tā hěn piàoliang.',d:'She is very pretty.'},
{u:4,h:'熊猫很可爱。',p:'Xióngmāo hěn kě’ài.',d:'Pandas are very cute.'},
{u:4,h:'他是我最喜欢的篮球运动员。',p:'Tā shì wǒ zuì xǐhuan de lánqiú yùndòngyuán.',d:'He is my favorite basketball player.'},
{u:4,h:'最喜欢的动物是熊猫。',p:'Zuì xǐhuan de dòngwù shì xióngmāo.',d:'The favorite animal is the panda.'},
{u:4,h:'我最喜欢的动物是熊猫。',p:'Wǒ zuì xǐhuan de dòngwù shì xióngmāo.',d:'My favorite animal is the panda.'},
{u:4,h:'姓名是什么？',p:'Xìngmíng shì shénme?',d:'What is the full name?'}, {u:4,h:'国籍是什么？',p:'Guójí shì shénme?',d:'What is the nationality?'},
{u:4,h:'出生地是哪里？',p:'Chūshēngdì shì nǎli?',d:'Where is the place of birth?'},
// Unit 5: numbers, phone, address, email
{u:5,h:'你的电话号码是55546998吗？',p:'Nǐ de diànhuà hàomǎ shì 55546998 ma?',d:'Is your phone number 55546998?'},
{u:5,h:'这是我家的电话号码。',p:'Zhè shì wǒ jiā de diànhuà hàomǎ.',d:'This is my home phone number.'},
{u:5,h:'你的手机号码是多少？',p:'Nǐ de shǒujī hàomǎ shì duōshao?',d:'What is your mobile phone number?'},
{u:5,h:'我的手机号码是12081345761。',p:'Wǒ de shǒujī hàomǎ shì 12081345761.',d:'My mobile phone number is 12081345761.'},
{u:5,h:'你住在哪里？',p:'Nǐ zhù zài nǎli?',d:'Where do you live?'}, {u:5,h:'我住在公园路19号。',p:'Wǒ zhù zài Gōngyuán Lù shíjiǔ hào.',d:'I live at 19 Park Road.'},
{u:5,h:'你的地址是什么？',p:'Nǐ de dìzhǐ shì shénme?',d:'What is your address?'}, {u:5,h:'我的地址是大学路23号。',p:'Wǒ de dìzhǐ shì Dàxué Lù èrshísān hào.',d:'My address is 23 University Road.'},
{u:5,h:'你的电子邮箱是什么？',p:'Nǐ de diànzǐ yóuxiāng shì shénme?',d:'What is your email address?'},
{u:5,h:'我的电子邮箱是马克。',p:'Wǒ de diànzǐ yóuxiāng shì Mǎkè.',d:'My email address is Mark.'},
{u:5,h:'你可以给我打电话。',p:'Nǐ kěyǐ gěi wǒ dǎ diànhuà.',d:'You can call me.'}, {u:5,h:'可以给我打电话吗？',p:'Kěyǐ gěi wǒ dǎ diànhuà ma?',d:'Can you call me?'},
{u:5,h:'收到，谢谢！',p:'Shōudào, xièxie!',d:'Received, thank you!'}, {u:5,h:'我收到新短信。',p:'Wǒ shōudào xīn duǎnxìn.',d:'I received a new text message.'},
{u:5,h:'发件人是谁？',p:'Fājiànrén shì shéi?',d:'Who is the sender?'}, {u:5,h:'请发送短信。',p:'Qǐng fāsòng duǎnxìn.',d:'Please send a text message.'}
];

const DIALOGUE_Q = [
// Unit 1
{u:1,q:'How do you ask for someone’s name in Chinese?',a:'你叫什么名字？'}, {u:1,q:'How do you politely ask: “May I ask, what is your name?”',a:'请问，你叫什么名字？'},
{u:1,q:'How do you say: “My name is Wang Yu.”',a:'我叫王玉。'}, {u:1,q:'How do you say: “And you?”',a:'你呢？'},
{u:1,q:'How do you say: “Nice to meet you.”',a:'认识你很高兴。'}, {u:1,q:'How do you say: “My surname is Wang.”',a:'我姓王。'},
{u:1,q:'How do you say: “Hello everyone!”',a:'大家好！'}, {u:1,q:'How do you say: “My Chinese name is Mark.”',a:'我的中文名字是马克。'},
// Unit 2
{u:2,q:'How do you ask: “Are you Japanese?”',a:'你是日本人吗？'}, {u:2,q:'How do you answer: “No, I am not Japanese.”',a:'不是，我不是日本人。'},
{u:2,q:'How do you ask: “Where are you from?”',a:'你是哪里人？'}, {u:2,q:'How do you ask: “What nationality are you?”',a:'你是哪国人？'},
{u:2,q:'How do you say: “I am Chinese.”',a:'我是中国人。'}, {u:2,q:'How do you say: “I am German.”',a:'我是德国人。'},
{u:2,q:'How do you ask: “Do you live in London?”',a:'你住在伦敦吗？'}, {u:2,q:'How do you say: “I live in Beijing.”',a:'我住在北京。'},
{u:2,q:'How do you say: “They are movie stars.”',a:'他们是电影明星。'}, {u:2,q:'How do you say: “But they are not American.”',a:'但是他们不是美国人。'},
// Unit 3
{u:3,q:'How do you ask: “Is she your younger sister?”',a:'她是你妹妹吗？'}, {u:3,q:'How do you say: “This is my younger brother.”',a:'这是我弟弟。'},
{u:3,q:'How do you ask about the father’s job?',a:'你爸爸做什么工作？'}, {u:3,q:'How do you say: “He is a doctor.”',a:'他是医生。'},
{u:3,q:'How do you ask: “Where does your mother work?”',a:'你妈妈在哪里工作？'}, {u:3,q:'How do you say: “She works in a hospital.”',a:'她在医院工作。'},
{u:3,q:'How do you say: “Dad and mom are both doctors.”',a:'爸爸妈妈都是医生。'}, {u:3,q:'How do you say: “This is a photo of my family.”',a:'这是我家的照片。'},
// Unit 4
{u:4,q:'How do you ask: “Who is he?”',a:'他是谁？'}, {u:4,q:'How do you ask: “How old is he?”',a:'他多大？'},
{u:4,q:'How do you say: “I do not know.”',a:'我不知道。'}, {u:4,q:'How do you say: “He is really tall!”',a:'他真高！'},
{u:4,q:'How do you say: “He is my favorite basketball player.”',a:'他是我最喜欢的篮球运动员。'}, {u:4,q:'How do you say: “Pandas are very cute.”',a:'熊猫很可爱。'},
{u:4,q:'How do you ask: “Where is he from?”',a:'他是哪里人？'}, {u:4,q:'How do you say: “He is from Shanghai.”',a:'他是上海人。'},
// Unit 5
{u:5,q:'How do you ask for someone’s mobile phone number?',a:'你的手机号码是多少？'}, {u:5,q:'How do you ask for someone’s phone number?',a:'你的电话号码是多少？'},
{u:5,q:'How do you ask: “Where do you live?”',a:'你住在哪里？'}, {u:5,q:'How do you ask for someone’s address?',a:'你的地址是什么？'},
{u:5,q:'How do you ask for someone’s email address?',a:'你的电子邮箱是什么？'}, {u:5,q:'How do you say: “I live at 19 Park Road.”',a:'我住在公园路19号。'},
{u:5,q:'How do you say: “You can call me.”',a:'你可以给我打电话。'}, {u:5,q:'How do you say: “Received, thank you!”',a:'收到，谢谢！'},
{u:5,q:'How do you ask: “Who is the sender?”',a:'发件人是谁？'}, {u:5,q:'How do you say: “Please send a text message.”',a:'请发送短信。'}
];
